/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthButton: typeof import('./components/auth/Button.vue')['default']
    AuthDeleteRecipeButton: typeof import('./components/auth/DeleteRecipeButton.vue')['default']
    AuthProfile: typeof import('./components/auth/Profile.vue')['default']
    AuthSignInModal: typeof import('./components/auth/SignInModal.vue')['default']
    AuthSignUpModal: typeof import('./components/auth/SignUpModal.vue')['default']
    BaseButton: typeof import('./components/base/Button.vue')['default']
    BaseCheckbox: typeof import('./components/base/Checkbox.vue')['default']
    BaseChip: typeof import('./components/base/Chip.vue')['default']
    BaseCircularIconButton: typeof import('./components/base/CircularIconButton.vue')['default']
    BaseDivider: typeof import('./components/base/Divider.vue')['default']
    BaseDropdown: typeof import('./components/base/Dropdown.vue')['default']
    BaseInput: typeof import('./components/base/Input.vue')['default']
    BaseLink: typeof import('./components/base/Link.vue')['default']
    BaseLoader: typeof import('./components/base/Loader.vue')['default']
    BaseModal: typeof import('./components/base/Modal.vue')['default']
    BaseTextarea: typeof import('./components/base/Textarea.vue')['default']
    BaseTypeahead: typeof import('./components/base/Typeahead.vue')['default']
    BaseTypography: typeof import('./components/base/Typography.vue')['default']
    CategoryTabsIconAppetizer: typeof import('./components/category-tabs/icon/appetizer.vue')['default']
    CategoryTabsIconMexican: typeof import('./components/category-tabs/icon/mexican.vue')['default']
    CategoryTabsIconPasta: typeof import('./components/category-tabs/icon/pasta.vue')['default']
    CategoryTabsIconPizza: typeof import('./components/category-tabs/icon/pizza.vue')['default']
    CategoryTabsIconSalad: typeof import('./components/category-tabs/icon/salad.vue')['default']
    CategoryTabsIconSauce: typeof import('./components/category-tabs/icon/sauce.vue')['default']
    CategoryTabsIconSoup: typeof import('./components/category-tabs/icon/soup.vue')['default']
    CategoryTabsIconSushi: typeof import('./components/category-tabs/icon/sushi.vue')['default']
    CategoryTabsItem: typeof import('./components/category-tabs/item.vue')['default']
    CategoryTabsList: typeof import('./components/category-tabs/list.vue')['default']
    EditRecipeAddIngredientModal: typeof import('./components/edit-recipe/AddIngredientModal.vue')['default']
    EditRecipeAddStepModal: typeof import('./components/edit-recipe/AddStepModal.vue')['default']
    ImageCloudinary: typeof import('./components/image/Cloudinary.vue')['default']
    LayoutContainer: typeof import('./components/layout/Container.vue')['default']
    LayoutHeader: typeof import('./components/layout/Header.vue')['default']
    LayoutPageLoader: typeof import('./components/layout/PageLoader.vue')['default']
    RecipeDetailsHeroImage: typeof import('./components/recipe-details/HeroImage.vue')['default']
    RecipesListDeleteRecipe: typeof import('./components/recipes-list/DeleteRecipe.vue')['default']
    RecipesListDeleteRecipeModal: typeof import('./components/recipes-list/DeleteRecipeModal.vue')['default']
    RecipesListFilterModal: typeof import('./components/recipes-list/filter-modal.vue')['default']
    RecipesListGrid: typeof import('./components/recipes-list/Grid.vue')['default']
    RecipesListItem: typeof import('./components/recipes-list/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingListShoppingList: typeof import('./components/shopping-list/ShoppingList.vue')['default']
    ShoppingListShoppingListAddItemField: typeof import('./components/shopping-list/ShoppingListAddItemField.vue')['default']
    ShoppingListShoppingListItem: typeof import('./components/shopping-list/ShoppingListItem.vue')['default']
  }
}
